# Copy this file to pesiki-bot repo as .github/workflows/deploy.yml
# Push to main → deploy on x260 (self-hosted runner)

name: Deploy to x260

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, x260, linux]
    if: github.repository == 'GlebkaF/pesiki-bot'
    environment:
      name: x260
      url: https://github.com/GlebkaF/pesiki-bot/actions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run with docker compose
        run: docker compose up -d --build
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
